uploads = []
outputs = []

[[generated]]
id = "iKOH-kodMlqtCZcMbsWqG"
uri = "file://artifacts/food-truck-marketplace/public/images/hero-bg.png"
type = "image"
title = "food truck in riyadh"

[[generated]]
id = "duKcPIfxXtDfc3JAZKim1"
uri = "file://artifacts/food-truck-marketplace/public/images/truck-coffee.png"
type = "image"
title = "coffee food truck"

[[generated]]
id = "IlnTt134FpuYh75SqM6N9"
uri = "file://artifacts/food-truck-marketplace/public/images/truck-burger.png"
type = "image"
title = "burger food truck"

[[generated]]
id = "2Dcs8phF3UAg2ZRoGbn-h"
uri = "file://artifacts/food-truck-marketplace/public/images/truck-shawarma.png"
type = "image"
title = "shawarma food truck"
